# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{trace-util-adv}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2009-10-28}
  s.description = %q{
      Configure tracing using context sensitive filters, appenders, output templates in a completely non-intrusive fashion. 
      Tracing can even be applied runtime as a response when certain conditions occur}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/README",
     "lib/TODO.txt",
     "lib/action_handler.rb",
     "lib/appenders/appender.rb",
     "lib/appenders/appender_registration.rb",
     "lib/appenders/base_appender.rb",
     "lib/appenders/file_appender.rb",
     "lib/appenders/html_appender.rb",
     "lib/appenders/logger_appender.rb",
     "lib/appenders/stream_appender.rb",
     "lib/appenders/template_log_appender.rb",
     "lib/appenders/xml_appender.rb",
     "lib/core_extensions.rb",
     "lib/filters/base_filters.rb",
     "lib/filters/composite_filters.rb",
     "lib/filters/filter_factory.rb",
     "lib/filters/message_filters.rb",
     "lib/filters/tracing_filter.rb",
     "lib/output_templates.rb",
     "lib/rule_match.rb",
     "lib/sample_filters.rb",
     "lib/templates/base_template.rb",
     "lib/templates/html_template.rb",
     "lib/templates/string_template.rb",
     "lib/templates/trace_output_handler.rb",
     "lib/templates/xml_template.rb",
     "lib/test_action_handler.rb",
     "lib/test_appender.rb",
     "lib/test_file_appender.rb",
     "lib/test_filters.rb",
     "lib/test_filters_chain.rb",
     "lib/test_filters_create.rb",
     "lib/test_html_appender.rb",
     "lib/test_special_filters.rb",
     "lib/test_xml_appender.rb",
     "lib/test_xml_gen.rb",
     "lib/trace-util-adv.rb",
     "lib/trace_appenders.rb",
     "lib/trace_calls.rb",
     "lib/trace_ext.rb",
     "lib/trace_filters.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/trace-util-adv_spec.rb",
     "trace-util-adv.gemspec"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/trace-util-adv}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{adds advancing tracing capability to your ruby code}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/trace-util-adv_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

